### ISSUE TITLE
Any reason to not use @commands in octoprint?

### ISSUE THREAD

**Issue by codingcatgirl** [SinisterRj/OctoPrint-MacroSteps#1]
This would avoid going through the printer using M118. Would be nice to have that as an optional feature.

**Comment by SinisterRj** [comment]
My first attempt was to use @commands, but they don't work with Klipper macros. So, to use it with Klipper (my personal objective) this was the solution. Anyway there aren't too much commands to make the plugin work, so the impact on the communication are negligible. But I'll consider it in a future release.
